Repository embermap/ember-cli-fastboot-testing, pull requests merged in 2023-03, with the labels that each got.

#763 update yarn.lock to fix CI
  yarn.lock
Labels: internal

#764 run `npx ember-cli-update --to=4.11.0` to align with blueprint
  .ember-cli
  .eslintrc.js
  .github/workflows/ci.yml
  .gitignore
  .prettierrc.js
  addon-test-support/index.js
  config/environment.js
  ember-cli-build.js
  package.json
  tests/dummy/config/addon-docs.js
  tests/dummy/config/deploy.js
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/dummy/config/environment.js
  vendor/.gitkeep
  yarn.lock
Labels: internal

#762 Config exports function rather than object
  blueprints/fastboot-test-config/files/__config__/fastboot-testing.js
  lib/helpers.js
  tests/dummy/app/templates/docs/fastboot-configuration.md
  tests/dummy/config/fastboot-testing.js
Labels: Feature / Enhancement

#765 Make fastboot peerDependency
  .github/workflows/ci.yml
  package.json
  tests/dummy/config/ember-try.js
  yarn.lock
Labels: Feature / Enhancement

#631 disable `outputReady` hook logic in production
  index.js
Labels: enhancement

#766 Bump dependencies
  .github/workflows/ci.yml
  package.json
  tests/dummy/config/ember-try.js
  yarn.lock
Labels: dependencies

#773 Fix typo in config path example
  tests/dummy/app/templates/docs/fastboot-configuration.md
Labels: documentation
